import ProjectDescription


let workspace = Workspace(
    name: "HGDGDS",
    projects: [
        "./**"
    ],
    schemes: [
//        .scheme(
//            name: "Dev-HGDGDS",
//            buildAction: .buildAction(targets: [.project(path: "./App", target: "HGDGDS")]),
//            testAction: nil,
//            runAction: .runAction(configuration: .debug),
//            archiveAction: .archiveAction(configuration: .debug),
//            profileAction: .profileAction(configuration: .debug),
//            analyzeAction: .analyzeAction(configuration: .debug)
//        ),
//        .scheme(
//            name: "PROD-HGDGDS",
//            buildAction: .buildAction(targets: [.project(path: "./App", target: "HGDGDS")]),
//            testAction: nil,
//            runAction: .runAction(configuration: .release),
//            archiveAction: .archiveAction(configuration: .release),
//            profileAction: .profileAction(configuration: .release),
//            analyzeAction: .analyzeAction(configuration: .release)
//        ),
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
